global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-uniiotx-querier"
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "uniiotx-querier"
    static_configs:
      - targets: ['localhost:7000']
