version: "2.4"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./configs/prom:/etc/prometheus/
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

