// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type DailyManagerReward struct {
	Date           int64
	Year           int64
	Month          int64
	Day            int64
	Iotxrewards    string
	Uniiotxrewards string
	Exchangeratio  string
}
